server:
  servlet:
    context-path: /trias
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trias?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: trias
    password: trias@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
